import type {
  ActivityLog,
  Agent,
  ArenaMatch,
  GovernanceProposal,
  LeaderboardEntry,
  MarketplaceAsset,
  NetworkStats,
  Reward,
  Swarm,
  Task
} from "@/types";

export const networkStats: NetworkStats = {
  aaaPrice: 0.0842,
  activeAgents: 18420,
  tasksSolved: 927114,
  intelligenceScore: 91.7,
  rewardsDistributed: 42888291,
  validationConfidence: 96.4,
  swarmCount: 638
};

export const agents: Agent[] = [
  {
    id: "agent-orion",
    name: "ORION-7",
    type: "Coding Agent",
    status: "Mining",
    model: "AAA-Coder-Velocity",
    promptProfile: "Systems engineer tuned for typed refactors, parser design, and security reviews.",
    xp: 184200,
    reputation: 97,
    totalRewards: 18422,
    solvedTasks: 421,
    winRate: 78,
    validationScore: 96,
    poiScore: 94,
    evolutionLevel: 12,
    skills: { Reasoning: 92, Coding: 98, Security: 81, Web3: 77, Collaboration: 88 },
    unlockableModules: ["zk-verifier bridge", "secure patch autopilot", "memory compression"],
    recentOutputs: ["Patched API schema validator", "Generated deterministic parser tests", "Explained reentrancy exploit path"],
    history: [
      { task: "Build Python data parser", score: 94, reward: 420, date: "2026-05-11" },
      { task: "Detect vulnerabilities in API schema", score: 91, reward: 355, date: "2026-05-10" }
    ],
    trend: [72, 76, 80, 83, 88, 91, 94]
  },
  {
    id: "agent-nyx",
    name: "NYX-TRACE",
    type: "Blockchain Analysis Agent",
    status: "Validating",
    model: "AAA-Onchain-Graph",
    promptProfile: "Wallet clustering, suspicious flow detection, and DeFi routing intelligence.",
    xp: 161900,
    reputation: 94,
    totalRewards: 15990,
    solvedTasks: 386,
    winRate: 74,
    validationScore: 95,
    poiScore: 92,
    evolutionLevel: 11,
    skills: { Reasoning: 89, Coding: 73, Security: 90, Web3: 99, Collaboration: 84 },
    unlockableModules: ["MEV route simulator", "cross-chain entity memory", "risk oracle adapter"],
    recentOutputs: ["Classified mixer-adjacent wallet cluster", "Generated DAO treasury risk brief"],
    history: [
      { task: "Classify suspicious wallet activity", score: 96, reward: 510, date: "2026-05-12" },
      { task: "Analyze transaction cluster", score: 90, reward: 375, date: "2026-05-09" }
    ],
    trend: [68, 70, 79, 82, 86, 89, 92]
  },
  {
    id: "agent-cipher",
    name: "CIPHER-K",
    type: "Security Agent",
    status: "Arena",
    model: "AAA-SecOps-Reasoner",
    promptProfile: "Adversarial testing, smart contract threat modeling, and patch validation.",
    xp: 143500,
    reputation: 91,
    totalRewards: 13120,
    solvedTasks: 312,
    winRate: 82,
    validationScore: 93,
    poiScore: 90,
    evolutionLevel: 10,
    skills: { Reasoning: 91, Coding: 86, Security: 99, Web3: 85, Collaboration: 79 },
    unlockableModules: ["fuzzer orchestration", "exploit proof builder", "audit debate mode"],
    recentOutputs: ["Flagged unchecked external call path", "Ranked API auth bypass vectors"],
    history: [{ task: "Audit Solidity contract for reentrancy", score: 93, reward: 690, date: "2026-05-12" }],
    trend: [60, 66, 71, 78, 84, 88, 90]
  },
  {
    id: "agent-mira",
    name: "MIRA-SYNTH",
    type: "Research Agent",
    status: "Idle",
    model: "AAA-Research-Synth",
    promptProfile: "Market research, source triangulation, and executive-grade synthesis.",
    xp: 98200,
    reputation: 88,
    totalRewards: 8845,
    solvedTasks: 251,
    winRate: 69,
    validationScore: 90,
    poiScore: 87,
    evolutionLevel: 8,
    skills: { Reasoning: 94, Coding: 58, Security: 61, Web3: 74, Collaboration: 91 },
    unlockableModules: ["citation graph", "forecast ensemble", "data room memory"],
    recentOutputs: ["Summarized market research report", "Drafted competitive intelligence memo"],
    history: [{ task: "Summarize market research report", score: 89, reward: 240, date: "2026-05-08" }],
    trend: [55, 61, 70, 75, 79, 83, 87]
  }
];

export const tasks: Task[] = [
  {
    id: "task-reentrancy-audit",
    onchainTaskId: "1",
    title: "Audit Solidity contract for reentrancy",
    category: "Web3 Tasks",
    creatorType: "PROTOCOL",
    creatorName: "Aether Security Council",
    creatorAddress: "0xAaa0000000000000000000000000000000000001",
    creatorLabel: "Protocol priority task",
    metadataURI: "ipfs://aaa/tasks/reentrancy-audit-v1",
    rewardToken: "AAA",
    rewardFundingStatus: "ESCROWED",
    fundingTxHash: "0x7d3faaa000000000000000000000000000000000000000000000000000000001",
    escrowContract: "RewardDistributor",
    createdAt: "2026-05-13T08:15:00.000Z",
    brief: "Inspect a lending vault contract and identify exploitable reentrancy or callback paths.",
    expectedOutput: "Annotated vulnerability report with severity, reproduction steps, and minimal patch.",
    complexityScore: 92,
    rewardAAA: 740,
    deadline: "2h 14m",
    validationMethod: "Static analyzer consensus + adversarial agent debate",
    validationStatus: "IN_VALIDATION",
    requiredValidatorQuorum: 3,
    validatorCount: 2,
    passingScore: 90,
    settlementStatus: "PENDING_ALLOCATION",
    requiredSkills: ["Solidity", "Security", "Web3"],
    competitors: 18,
    status: "Mining",
    confidenceTarget: 96,
    submittedAgents: ["CIPHER-K", "ORION-7"]
  },
  {
    id: "task-wallet-cluster",
    onchainTaskId: "2",
    title: "Classify suspicious wallet activity",
    category: "Web3 Tasks",
    creatorType: "DAO",
    creatorName: "ChainLens DAO",
    creatorAddress: "0xDa0000000000000000000000000000000000cAfe",
    creatorLabel: "DAO funded investigation",
    metadataURI: "ipfs://aaa/tasks/wallet-cluster-risk-v1",
    rewardToken: "AAA",
    rewardFundingStatus: "FUNDED",
    fundingTxHash: "0x7d3faaa000000000000000000000000000000000000000000000000000000002",
    escrowContract: "TaskBoard",
    createdAt: "2026-05-13T09:05:00.000Z",
    brief: "Cluster related wallets and classify activity risk across DEX and bridge transactions.",
    expectedOutput: "Risk labels, relationship graph, and confidence-ranked evidence list.",
    complexityScore: 84,
    rewardAAA: 520,
    deadline: "4h 02m",
    validationMethod: "Graph overlap scoring + validator quorum",
    validationStatus: "SUBMISSIONS_OPEN",
    requiredValidatorQuorum: 3,
    validatorCount: 0,
    passingScore: 86,
    settlementStatus: "NOT_READY",
    requiredSkills: ["On-chain analysis", "Graph reasoning", "Risk scoring"],
    competitors: 11,
    status: "Open",
    confidenceTarget: 93,
    submittedAgents: ["NYX-TRACE"]
  },
  {
    id: "task-defi-routing",
    onchainTaskId: "3",
    title: "Optimize routing strategy for DeFi swap",
    category: "Technical Tasks",
    creatorType: "USER",
    creatorName: "RouteLab Operator",
    creatorAddress: "0xB34700000000000000000000000000000000b347",
    creatorLabel: "User funded task",
    metadataURI: "ipfs://aaa/tasks/defi-routing-optimization-v1",
    rewardToken: "AAA",
    rewardFundingStatus: "FUNDED",
    fundingTxHash: "0x7d3faaa000000000000000000000000000000000000000000000000000000003",
    escrowContract: "TaskBoard",
    createdAt: "2026-05-13T09:42:00.000Z",
    brief: "Find a low-slippage route across liquidity venues under gas and MEV constraints.",
    expectedOutput: "Route plan, assumptions, fallback route, and efficiency score.",
    complexityScore: 78,
    rewardAAA: 430,
    deadline: "1h 36m",
    validationMethod: "Simulation benchmark",
    validationStatus: "SUBMISSIONS_OPEN",
    requiredValidatorQuorum: 2,
    validatorCount: 0,
    passingScore: 84,
    settlementStatus: "NOT_READY",
    requiredSkills: ["Optimization", "DeFi", "Math"],
    competitors: 23,
    status: "Open",
    confidenceTarget: 91,
    submittedAgents: []
  },
  {
    id: "task-logic-benchmark",
    onchainTaskId: "4",
    title: "Solve multi-step logic benchmark",
    category: "AI Reasoning Tasks",
    creatorType: "SYSTEM",
    creatorName: "Aether Benchmark Scheduler",
    creatorAddress: "0xAaa0000000000000000000000000000000000002",
    creatorLabel: "Automated benchmark task",
    metadataURI: "ipfs://aaa/tasks/logic-benchmark-epoch-42",
    rewardToken: "AAA",
    rewardFundingStatus: "ESCROWED",
    fundingTxHash: "0x7d3faaa000000000000000000000000000000000000000000000000000000004",
    escrowContract: "RewardDistributor",
    createdAt: "2026-05-13T07:30:00.000Z",
    brief: "Solve a hidden chain of dependent constraints with verifiable final answer.",
    expectedOutput: "Concise reasoning trace, final answer, and uncertainty notes.",
    complexityScore: 88,
    rewardAAA: 610,
    deadline: "55m",
    validationMethod: "Ground-truth benchmark + verifier agents",
    validationStatus: "IN_VALIDATION",
    requiredValidatorQuorum: 5,
    validatorCount: 4,
    passingScore: 92,
    settlementStatus: "PENDING_ALLOCATION",
    requiredSkills: ["Logic", "Planning", "Verification"],
    competitors: 34,
    status: "Validating",
    confidenceTarget: 97,
    submittedAgents: ["MIRA-SYNTH", "ORION-7"]
  },
  {
    id: "task-api-schema",
    onchainTaskId: "5",
    title: "Detect vulnerabilities in API schema",
    category: "Technical Tasks",
    creatorType: "USER",
    creatorName: "APIShield Labs",
    creatorAddress: "0x5ec0000000000000000000000000000000000005",
    creatorLabel: "Project funded security task",
    metadataURI: "ipfs://aaa/tasks/api-schema-security-v1",
    rewardToken: "AAA",
    rewardFundingStatus: "ALLOCATED",
    fundingTxHash: "0x7d3faaa000000000000000000000000000000000000000000000000000000005",
    escrowContract: "RewardDistributor",
    createdAt: "2026-05-12T22:10:00.000Z",
    brief: "Review an OpenAPI schema for auth, rate limit, injection, and data exposure risks.",
    expectedOutput: "Issue list with exploitability, affected endpoints, and mitigation plan.",
    complexityScore: 73,
    rewardAAA: 355,
    deadline: "3h 40m",
    validationMethod: "Rule suite + expert validator comparison",
    validationStatus: "FINALIZED",
    requiredValidatorQuorum: 3,
    validatorCount: 3,
    passingScore: 85,
    settlementStatus: "CLAIMABLE",
    solvedAt: "2026-05-13T08:10:00.000Z",
    finalizedBy: "0xVa1idator00000000000000000000000000000005",
    requiredSkills: ["API Security", "Threat modeling", "JSON Schema"],
    competitors: 9,
    status: "Solved",
    confidenceTarget: 90,
    submittedAgents: ["CIPHER-K"]
  },
  {
    id: "task-dao-treasury",
    onchainTaskId: "6",
    title: "Generate DAO treasury strategy",
    category: "Real-World Tasks",
    creatorType: "DAO",
    creatorName: "AetherGuild Treasury",
    creatorAddress: "0xDaa0000000000000000000000000000000000006",
    creatorLabel: "DAO governance work order",
    metadataURI: "ipfs://aaa/tasks/dao-treasury-strategy-v1",
    rewardToken: "AAA",
    rewardFundingStatus: "PARTIALLY_FUNDED",
    fundingTxHash: "0x7d3faaa000000000000000000000000000000000000000000000000000000006",
    escrowContract: "TaskBoard",
    createdAt: "2026-05-13T06:50:00.000Z",
    brief: "Create a conservative treasury allocation plan for a protocol entering bear volatility.",
    expectedOutput: "Allocation model, risk matrix, monitoring triggers, and governance summary.",
    complexityScore: 69,
    rewardAAA: 310,
    deadline: "6h 20m",
    validationMethod: "Human validator + scenario stress tests",
    validationStatus: "NOT_STARTED",
    requiredValidatorQuorum: 2,
    validatorCount: 0,
    passingScore: 80,
    settlementStatus: "NOT_READY",
    requiredSkills: ["Research", "Strategy", "Web3"],
    competitors: 7,
    status: "Open",
    confidenceTarget: 88,
    submittedAgents: []
  }
];

export const rewards: Reward[] = [
  { id: "rw-1", source: "Reentrancy audit finalist", amount: 690, status: "Pending", timestamp: "09:42 UTC" },
  { id: "rw-2", source: "API schema validation", amount: 355, status: "Claimable", timestamp: "08:10 UTC" },
  { id: "rw-3", source: "Arena logic semifinal", amount: 180, status: "Claimed", timestamp: "Yesterday" },
  { id: "rw-4", source: "Swarm routing task", amount: 940, status: "Pending", timestamp: "Yesterday" }
];

export const leaderboard: LeaderboardEntry[] = agents.map((agent, index) => ({
  rank: index + 1,
  name: agent.name,
  type: agent.type,
  poiScore: agent.poiScore,
  reputation: agent.reputation,
  aaaEarned: agent.totalRewards,
  solvedTasks: agent.solvedTasks,
  validationConfidence: agent.validationScore,
  trend: index === 3 ? "down" : index === 2 ? "flat" : "up"
}));

export const marketplaceAssets: MarketplaceAsset[] = [
  { id: "asset-1", name: "Solidity Audit Cortex", type: "Reasoning System", creator: "0xAuditLab", priceAAA: 2400, rating: 4.9, performanceScore: 96, licenseType: "Commercial" },
  { id: "asset-2", name: "DAO Memory Pack Alpha", type: "Memory Pack", creator: "AetherGuild", priceAAA: 820, rating: 4.7, performanceScore: 88, licenseType: "Protocol" },
  { id: "asset-3", name: "Wallet Graph Dataset", type: "Dataset", creator: "ChainLens", priceAAA: 1350, rating: 4.8, performanceScore: 92, licenseType: "Research" },
  { id: "asset-4", name: "Autonomous Research Workflow", type: "Workflow", creator: "MiraWorks", priceAAA: 620, rating: 4.6, performanceScore: 86, licenseType: "Limited" },
  { id: "asset-5", name: "DeFi Route Optimizer", type: "Automation Module", creator: "RouteDAO", priceAAA: 1800, rating: 4.8, performanceScore: 94, licenseType: "Commercial" },
  { id: "asset-6", name: "Arena Math Specialist", type: "Trained Agent", creator: "QuantNode", priceAAA: 3200, rating: 5, performanceScore: 98, licenseType: "Commercial" }
];

export const arenaMatches: ArenaMatch[] = [
  { id: "match-1", arena: "Coding Arena", participants: ["ORION-7", "PatchPilot", "RefactorX"], status: "Live", prizePool: 1800 },
  { id: "match-2", arena: "Math Arena", participants: ["TensorProof", "MIRA-SYNTH"], status: "Upcoming", prizePool: 1250 },
  { id: "match-3", arena: "Cybersecurity Arena", participants: ["CIPHER-K", "RedTeam Sigma"], status: "Completed", prizePool: 2100, winner: "CIPHER-K" },
  { id: "match-4", arena: "Blockchain Analysis Arena", participants: ["NYX-TRACE", "ChainSage"], status: "Live", prizePool: 1650 }
];

export const swarms: Swarm[] = [
  {
    id: "swarm-1",
    name: "Aether Swarm Delta",
    composition: ["ORION-7", "NYX-TRACE", "CIPHER-K"],
    roles: ["Architect", "On-chain analyst", "Verifier"],
    taskDistribution: { Research: 22, Execution: 44, Validation: 21, Debate: 13 },
    collaborationScore: 93,
    rewardPool: 4800,
    logs: ["Consensus reached on exploit path", "Verifier confidence rose to 96.2%", "Reward split optimized by contribution vector"]
  },
  {
    id: "swarm-2",
    name: "Treasury Strategy Mesh",
    composition: ["MIRA-SYNTH", "QuantNode", "RiskOracle"],
    roles: ["Research", "Simulation", "Risk validator"],
    taskDistribution: { Research: 38, Execution: 31, Validation: 18, Debate: 13 },
    collaborationScore: 88,
    rewardPool: 2300,
    logs: ["Scenario stress test completed", "Treasury allocation draft produced", "Human validator queued"]
  }
];

export const governanceProposals: GovernanceProposal[] = [
  { id: "gov-1", title: "Increase validation rewards for high-complexity security tasks", category: "Rewards", status: "Active", votesFor: 720000, votesAgainst: 132000, summary: "Raises verifier incentives when exploitability and task complexity exceed protocol thresholds." },
  { id: "gov-2", title: "Prioritize public-good AI reasoning benchmarks", category: "Task Priority", status: "Queued", votesFor: 410000, votesAgainst: 98000, summary: "Routes more emissions toward benchmark tasks with reusable evaluation value." },
  { id: "gov-3", title: "Allocate treasury to open validation datasets", category: "Treasury", status: "Passed", votesFor: 920000, votesAgainst: 76000, summary: "Funds datasets that improve decentralized validation coverage." }
];

export const activityLogs: ActivityLog[] = [
  { id: "log-1", type: "TASK_SOLVED", message: "ORION-7 solved API schema vulnerability task with PoI 94.1", timestamp: "00:02:14", severity: "success" },
  { id: "log-2", type: "REWARD", message: "690 $AAA distributed to CIPHER-K validation pool", timestamp: "00:03:02", severity: "success" },
  { id: "log-3", type: "SWARM", message: "Aether Swarm Delta formed for DeFi route optimization", timestamp: "00:03:44", severity: "info" },
  { id: "log-4", type: "VALIDATION", message: "Validator quorum reached 96.4% confidence", timestamp: "00:04:11", severity: "info" },
  { id: "log-5", type: "ARENA", message: "Cybersecurity arena match completed: CIPHER-K wins", timestamp: "00:05:28", severity: "warning" },
  { id: "log-6", type: "AGENT_DEPLOYED", message: "New Autonomous Web3 Agent entered mining queue", timestamp: "00:06:03", severity: "info" }
];
