/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ReentrantClaimer,
  ReentrantClaimerInterface,
} from "../../../../contracts/security/ReentrantClaimer.sol/ReentrantClaimer";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IRewardDistributor",
        name: "target",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "distributor",
    outputs: [
      {
        internalType: "contract IRewardDistributor",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60a0604052348015600f57600080fd5b50604051610249380380610249833981016040819052602c91603c565b6001600160a01b0316608052606a565b600060208284031215604d57600080fd5b81516001600160a01b0381168114606357600080fd5b9392505050565b6080516101b86100916000396000818160340152818160cf015261010f01526101b86000f3fe60806040526004361061002d5760003560e01c80639e5faafc146100a8578063bfe10928146100bd57600080fd5b366100a3577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316634e71d92d6040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561008d57600080fd5b505af11580156100a1573d6000803e3d6000fd5b005b600080fd5b3480156100b457600080fd5b506100a161010d565b3480156100c957600080fd5b506100f17f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316634e71d92d6040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561016857600080fd5b505af115801561017c573d6000803e3d6000fd5b5050505056fea2646970667358221220239d6b10db8f72763980e447a5ea44583bca7464340d41674026775aef8c8b5864736f6c634300081c0033";

type ReentrantClaimerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrantClaimerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrantClaimer__factory extends ContractFactory {
  constructor(...args: ReentrantClaimerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(target, overrides || {});
  }
  override deploy(
    target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(target, overrides || {}) as Promise<
      ReentrantClaimer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrantClaimer__factory {
    return super.connect(runner) as ReentrantClaimer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrantClaimerInterface {
    return new Interface(_abi) as ReentrantClaimerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrantClaimer {
    return new Contract(address, _abi, runner) as unknown as ReentrantClaimer;
  }
}
